import json

config_data = {
    "projection": {
        "dat_path": "./data",
        "field": "rho",
        "norm": [1,0,0],
        "save_path": "default",
        "zmin": "auto",
        "zmax": "auto",
        "begin": 0,
        "end": -1,
        "xyz_file": "./x_y_z.npz",
        "n_sph": 400,
        "n_car": 400,
        "fields_save_path": "./yt_fields",
        "is_reload": False,
        "reload_file": "./spherical_data.pkl",
        "save_pkl": True,
        "pkl_name": "./spherical_data.pkl",
        "fields_file_name": "fields",
        "auto_skip": True,
        "fields_list": ["rho", "e"],
        "dr": 0.0,
        "n_cut": 0
    },
    "synthesis": {
        "dat_path": "./data",
        "iwave": "171",
        "norm": [1,0,0],
        "rad_path": "default",
        "zmin": "auto",
        "zmax": "auto",
        "begin": 0,
        "end": -1,
        "xyz_file": "./x_y_z.npz",
        "n_sph": 400,
        "n_car": 400,
        "fields_save_path": "./yt_fields",
        "is_reload": False,
        "reload_file": "./spherical_data.pkl",
        "save_pkl": True,
        "pkl_name": "./spherical_data.pkl",
        "fields_file_name": "fields",
        "auto_skip": True,
        "fields_list": ["rho", "e"],
        "dr": 0.0,
        "n_cut": 0
    },
    "magline": {
        "dat_path": "./data",
        "p": [0.5,0.5,0.5],
        "frame": 0,
        "reload_file": None,
        "r_slice": 1.05,
        "xyz_file": "./x_y_z.npz",
        "n_sph": 400,
        "n_car": 400,
        "fields_save_path": "./yt_fields",
        "save_pkl": True,
        "pkl_name": "./spherical_data.pkl",
        "fields_file_name": "fields",
        "auto_skip": True,
        "dr": 0.0,
        "n_cut": 0,
        "radius": 0.02,
        "n_lines": 10
    },
    "view3D": {
        "dat_path": "./data",
        "iwave": '171',
        "field": 'rho',
        "frame": 0,
        "zmin": "auto",
        "zmax": "auto",
        "reload_file": None,
        "xyz_file": "./x_y_z.npz",
        "n_sph": 400,
        "n_car": 400,
        "fields_save_path": "./yt_fields",
        "save_pkl": True,
        "pkl_name": "./spherical_data.pkl",
        "fields_file_name": "fields",
        "auto_skip": True,
        "dr": 0.0,
        "n_cut": 0
    }
}

with open('config.json', 'w') as json_file:
    json.dump(config_data, json_file, indent=4)